version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/usr/share/nginx/html
    restart: always

  api:
    build: ./server
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: always

  db:
    image: mongodb
    volumes:
      - ./data:/data/db
    restart: always